# Generated by Django 3.2 on 2021-04-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.city')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planets',
                'db_table': 'planet',
            },
        ),
        migrations.CreateModel(
            name='Spaceship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DE', 'Decommissioned'), ('MA', 'Maintenance'), ('OP', 'Operational')], max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.location')),
            ],
            options={
                'verbose_name': 'Spaceship',
                'verbose_name_plural': 'Spaceships',
                'db_table': 'spaceship',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.planet'),
        ),
        migrations.AddField(
            model_name='city',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.planet'),
        ),
    ]
